LOG_LEVEL = "LOG_LEVEL"

TWITCH_USERNAME = "TWITCH_USERNAME"
TWITCH_ACCESS_TOKEN = "TWITCH_ACCESS_TOKEN"
TWITCH_CLIENT_ID = "TWITCH_CLIENT_ID"
TWITCH_CHANNEL = "TWITCH_CHANNEL"

KEY_PRESS_DURATION = "KEY_PRESS_DURATION"
KEY_PRESS_SCALE_FACTOR = "KEY_PRESS_SCALE_FACTOR"
KEY_PRESS_DURATION_MIN = "KEY_PRESS_DURATION_MIN"
KEY_PRESS_DURATION_MAX = "KEY_PRESS_DURATION_MAX"

KEY_INPUTS = "KEY_INPUTS"

KEY_PRESS_DURATION_DEFAULT = 1
KEY_PRESS_SCALE_FACTOR_DEFAULT = 0.05
KEY_PRESS_DURATION_MIN_DEFAULT = 1
KEY_PRESS_DURATION_MAX_DEFAULT = 10


